/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "first.h"

JNIEXPORT jint JNICALL Java_com_knjin_testjni_JniTest_add
  (JNIEnv * env, jobject this, jint x, jint y){
    return first(x, y);
  }
